import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const C=window.FORMIKAT_PITCH;
const projects=[
['Nach den Maschinen','Salinemuseum Halle','Ausstellungsdesign'],['Zukunftswerkstatt Salinemuseum','Salinemuseum Halle','Ausstellung · Medien'],['Total Real','Franckesche Stiftungen Halle','Ausstellungsdesign'],['MOVE! Verkehr macht Stadt','Verkehrsmuseum Dresden','Ausstellungsdesign'],['Streit.','Franckesche Stiftungen Halle','Ausstellungsdesign'],['Im Steinbruch der Zeit','Franckesche Stiftungen Halle','Ausstellungsdesign'],['Willhelmgrill','Willhelm Technologies','Produktdesign'],['Deltaslide','Open Source Community','Produktdesign'],['Ich.Fahr.Rad','Verkehrsmuseum Dresden','Ausstellungsdesign'],['Masse und Klasse','Stadtmuseum Halle','Ausstellungsdesign'],['Themenmöbel','Verkehrsmuseum Dresden','Mobile Einrichtung'],['Zukunftszentrum','BBR','Wettbewerbsentwurf']
];
const process=['BRIEFING','RECHERCHE','IDEE','PLANEN','UMSETZEN'];
const palette=C.palette||['#ff4b23','#e7ff3f','#5c6cff','#f4efe6'];
const app=document.querySelector('#app');
app.innerHTML=`<canvas id="gl"></canvas><div class="grain"></div><header><b>FORMIKAT</b><span>${String(C.id).padStart(2,'0')} / 30</span><button id="info">INFO</button></header><main><div class="eyebrow">EXPERIMENT ${String(C.id).padStart(2,'0')} · ${C.ref}</div><h1>${C.title}</h1><p class="pitch">${C.pitch}</p><div class="hint">${C.hint}</div></main><aside id="panel"><button id="close">×</button><small>FORMIKAT / ${C.ref}</small><h2>${C.title}</h2><p>${C.pitch}</p><p>FORMIKAT entwirft und entwickelt in den Bereichen Ausstellungs- und Produktgestaltung – vom ersten Impuls bis zur Umsetzung.</p><hr><b>IDEEN GREIFBAR MACHEN</b><p>Produktdesign · Ausstellungsdesign · Mobile Einrichtungen</p><p>Berliner Straße 5 · 06112 Halle (Saale)</p></aside><div id="label"></div><nav id="nav"></nav>`;
const css=`*{box-sizing:border-box}html,body,#app{margin:0;width:100%;height:100%;overflow:hidden;background:${C.bg||'#101010'};color:${C.fg||'#f4f1e9'};font-family:Arial,Helvetica,sans-serif}#gl{position:fixed;inset:0;width:100%;height:100%}.grain{pointer-events:none;position:fixed;inset:0;opacity:.09;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.7'/%3E%3C/svg%3E")}header{position:fixed;z-index:5;left:0;top:0;width:100%;padding:22px 26px;display:flex;gap:28px;align-items:center;mix-blend-mode:difference}header b{font-size:18px;letter-spacing:.08em}header span{font:12px monospace;opacity:.7}button{margin-left:auto;background:none;color:inherit;border:1px solid currentColor;border-radius:100px;padding:7px 13px;cursor:pointer}main{position:fixed;z-index:4;left:26px;bottom:25px;max-width:min(760px,calc(100vw - 52px));pointer-events:none}.eyebrow{font:11px monospace;letter-spacing:.12em;margin-bottom:12px;opacity:.7}h1{font-size:clamp(42px,8vw,118px);line-height:.82;letter-spacing:-.07em;margin:0;text-wrap:balance}.pitch{font-size:clamp(15px,1.5vw,21px);line-height:1.25;max-width:620px;margin:20px 0 10px}.hint{font:11px monospace;opacity:.65;text-transform:uppercase;letter-spacing:.08em}#panel{position:fixed;z-index:10;right:0;top:0;height:100%;width:min(430px,100%);background:#f1eee5;color:#111;padding:30px;transform:translateX(102%);transition:.45s cubic-bezier(.2,.8,.2,1);box-shadow:-20px 0 60px #0004}#panel.open{transform:none}#panel #close{font-size:24px;border:0}#panel h2{font-size:44px;letter-spacing:-.05em;line-height:.95;margin:60px 0 24px}#panel p{line-height:1.45}#panel hr{border:0;border-top:1px solid #111;margin:30px 0}#label{position:fixed;z-index:6;display:none;background:#f4efe6;color:#111;padding:10px 12px;font:12px monospace;pointer-events:none;max-width:240px}#nav{position:fixed;z-index:5;right:24px;bottom:24px;display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end;max-width:360px}#nav button{margin:0;font:10px monospace;padding:6px 8px;background:#1118;backdrop-filter:blur(8px)}@media(max-width:700px){h1{font-size:54px}main{bottom:70px}.pitch{max-width:90%}#nav{display:none}}`;
document.head.insertAdjacentHTML('beforeend',`<style>${css}</style>`);
const renderer=new THREE.WebGLRenderer({canvas:document.querySelector('#gl'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(C.bg||'#101010',C.fog||.025);const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,500);camera.position.set(0,5,18);
scene.add(new THREE.HemisphereLight(0xffffff,0x333333,2.4));const dl=new THREE.DirectionalLight(0xffffff,3);dl.position.set(5,10,8);scene.add(dl);
const group=new THREE.Group();scene.add(group);const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let hover=null,t=0,targetX=0,targetY=0;
const mat=(i,wire=false)=>new THREE.MeshStandardMaterial({color:palette[i%palette.length],roughness:.55,metalness:.05,wireframe:wire,transparent:true,opacity:wire?.45:1,side:THREE.DoubleSide});
function add(mesh,name,meta){mesh.userData={name,meta};group.add(mesh);return mesh}
function box(x,y,z,sx,sy,sz,i,name,meta){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),mat(i));m.position.set(x,y,z);return add(m,name,meta)}
function card(i,x,y,z,rot=0){const p=projects[i%projects.length];const m=box(x,y,z,3.2,2,.16,i,p[0],p[1]+' · '+p[2]);m.rotation.y=rot;return m}
function build(){const mode=C.mode;
if(mode==='expedition'){projects.forEach((p,i)=>{const a=i*.72,r=5+i*.52;card(i,Math.sin(a)*r,(i%3-1)*1.5,-i*3,Math.sin(a)*.5)});camera.position.set(0,1,16)}
else if(mode==='playground'){for(let i=0;i<30;i++){const m=box((i%6-2.5)*2.3,Math.random()*1.4-2,-Math.floor(i/6)*3,1.3,Math.random()*2+1,1.3,i,'Werkstück '+(i+1),process[i%5]);m.rotation.y=i*.37}camera.position.set(0,4,15)}
else if(mode==='house'){for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const m=card(i,Math.sin(a)*8,(i%4-1.5)*2,Math.cos(a)*8,a);m.scale.set(.8,.8,.8)}camera.position.set(0,1,18)}
else if(mode==='timeline'){process.forEach((p,i)=>{const m=box((i-2)*4,0,-i*3,2.4,2.4,2.4,i,p,'Vom ersten Impuls bis zur Umsetzung');m.rotation.set(.2,i*.25,.1)});projects.slice(0,7).forEach((p,i)=>card(i,(i-3)*3,-3,-15-i*1.2));camera.position.set(0,3,18)}
else if(mode==='doors'){projects.slice(0,10).forEach((p,i)=>{const x=(i%5-2)*4.2,z=-Math.floor(i/5)*8;const frame=new THREE.Mesh(new THREE.BoxGeometry(3.1,5,.25),mat(i,true));frame.position.set(x,0,z);add(frame,p[0],'PORTAL · '+p[1]);const door=box(x,0,z+.05,2.5,4.4,.12,i+1,p[0],p[2]);door.rotation.y=.25*(i%2?1:-1)});camera.position.set(0,1,14)}
else if(mode==='terrain'){const geo=new THREE.PlaneGeometry(45,45,45,45);const a=geo.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),y=a.getY(i);a.setZ(i,Math.sin(x*.45)*Math.cos(y*.35)*2+Math.sin((x+y)*.15))}geo.computeVertexNormals();const m=new THREE.Mesh(geo,mat(2,true));m.rotation.x=-Math.PI/2;m.position.y=-4;add(m,'Projektlandschaft','15 Jahre Ideen, Räume und Objekte');projects.forEach((p,i)=>{const a=i*.8,r=3+i*.65;const pin=box(Math.sin(a)*r,-2.5,Math.cos(a)*r,.35,2+.3*(i%4),.35,i,p[0],p[1])});camera.position.set(0,8,18)}
else if(mode==='city'){projects.forEach((p,i)=>{const x=(i%4-1.5)*3.5,z=-Math.floor(i/4)*4,h=2+(i*1.7)%7;box(x,-3+h/2,z,2.2,h,2.2,i,p[0],p[2])});camera.position.set(10,9,18)}
else if(mode==='orbit'){projects.forEach((p,i)=>{const a=i/projects.length*Math.PI*2,r=6+(i%3)*2;const g=i%2?new THREE.IcosahedronGeometry(1.2,1):new THREE.TorusKnotGeometry(.7,.2,60,8);const m=new THREE.Mesh(g,mat(i));m.position.set(Math.cos(a)*r,(i%4-1.5)*1.4,Math.sin(a)*r);add(m,p[0],p[2])});camera.position.set(0,4,19)}
else if(mode==='machine'){const core=box(0,0,0,6,4,3,0,'FORMIKAT','Ideen greifbar machen');for(let i=0;i<10;i++){const g=i%3===0?new THREE.CylinderGeometry(.6,.6,1.5,20):new THREE.BoxGeometry(1.3,1.3,1.3);const m=new THREE.Mesh(g,mat(i+1));m.position.set((i%5-2)*2.1,(Math.floor(i/5)-.5)*5,(i%2?2:-2));m.rotation.set(i*.2,i*.4,0);add(m,process[i%5],projects[i][0])}camera.position.set(0,3,17)}
else if(mode==='archive'){for(let i=0;i<40;i++){const m=box((i%8-3.5)*1.55,(Math.floor(i/8)-2)*1.2,-i%4,.95,.75,.18,i,projects[i%12][0],['Foto','CAD','Modell','Material','Film'][i%5]);m.rotation.z=(i%3-1)*.08}camera.position.set(0,0,17)}
else if(mode==='fragments'){projects.forEach((p,i)=>{const g=[new THREE.TorusGeometry(1,.18,12,40),new THREE.ConeGeometry(1,2,5),new THREE.OctahedronGeometry(1.2),new THREE.CylinderGeometry(.8,.8,2,12)][i%4];const m=new THREE.Mesh(g,mat(i,i%5===0));m.position.set((i%4-1.5)*4,(Math.floor(i/4)-1)*4,(i%3)*-2);m.rotation.set(i*.4,i*.2,i*.1);add(m,p[0],p[2])});camera.position.set(0,2,19)}
}
build();
projects.slice(0,5).forEach((p,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0')+' '+p[0];b.onclick=()=>{targetX=(i-2)*.35;targetY=i*.1};document.querySelector('#nav').appendChild(b)});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('pointermove',e=>{mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight*2-1);targetX=(e.clientX/innerWidth-.5)*2;targetY=(e.clientY/innerHeight-.5)*2;ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(group.children,false)[0];hover=hit?.object||null;const l=document.querySelector('#label');if(hover){l.style.display='block';l.style.left=e.clientX+14+'px';l.style.top=e.clientY+14+'px';l.innerHTML='<b>'+hover.userData.name+'</b><br>'+hover.userData.meta}else l.style.display='none'});
addEventListener('click',e=>{if(hover&&e.target.id==='gl'){group.children.forEach(o=>o.scale.setScalar(1));hover.scale.setScalar(1.45)}});addEventListener('wheel',e=>{camera.position.z=THREE.MathUtils.clamp(camera.position.z+e.deltaY*.008,7,35)},{passive:true});
document.querySelector('#info').onclick=()=>document.querySelector('#panel').classList.add('open');document.querySelector('#close').onclick=()=>document.querySelector('#panel').classList.remove('open');
function animate(){requestAnimationFrame(animate);t+=.006;group.rotation.y+=(targetX*.08-group.rotation.y)*.018;group.rotation.x+=(-targetY*.05-group.rotation.x)*.018;group.children.forEach((o,i)=>{if(C.motion!=='still'){o.rotation.y+=.0015*(i%3-1);o.position.y+=Math.sin(t*2+i)*.0008}});camera.lookAt(0,0,-3);renderer.render(scene,camera)}animate();