import fs from 'node:fs';

const pitches = [
['01-expedition','EXPEDITIONE','Expedition durch gebaute Ideen','Nach den Maschinen','scroll-flight'],
['02-playground','BRUNO SIMON','Die Werkstatt als Spielplatz','Willhelmgrill','drive'],
['03-house','SCHUMACHER 3D HOUSE','Das unmögliche FORMIKAT-Haus','Zukunftswerkstatt','house'],
['04-reconstructed-spaces','ANCIENT EGYPT 3D','Ausstellungen als digitale Räume','Im Steinbruch der Zeit','panorama'],
['05-process-story','THE OLDEST THING','Vom Impuls zum gebauten Ding','Deltaslide','timeline'],
['06-doors','DOORS','Jedes Projekt ist eine Tür','FORMIKAT Archiv','doors'],
['07-terrain','TERRAIN RIDER','Das Archiv wird Landschaft','MOVE! Verkehr macht Stadt','terrain'],
['08-city','DAT.CITY','Eine Stadt aus Projekten','15 Jahre FORMIKAT','city'],
['09-depth','OCEANX','Ein erzählerischer Tiefenraum','Nach den Maschinen','depth'],
['10-body-navigation','FACE FLIGHT','Navigation wird körperlich','Zukunftswerkstatt','face'],
['11-builder','4x4 BUILDER','Bau dir eine Ausstellung','Mongolei Baukasten','builder'],
['12-object','SNEAKERSKETCH','Aus Anschauen wird Anfassen','Willhelmgrill','configurator'],
['13-floorplan','PLANPOINT','Der Grundriss ist das Menü','Salinemuseum Halle','floorplan'],
['14-architectural-model','COMPOSITES ARCHITECTURE','Website als Architekturmodell','Zukunftszentrum','model'],
['15-garden','GARDEN','Der FORMIKAT-Objektgarten','Mobile Einrichtungen','garden'],
['16-lab','FACETLAB','Gestaltung als Experiment','Materiallabor','facets'],
['17-orbits','NASA EYES','Projekte im Orbit','FORMIKAT Kosmos','orbit'],
['18-perspectives','POVIEWIN','Ein Projekt, fünf Perspektiven','MOVE! Verkehr macht Stadt','perspective'],
['19-vault','PIXEL VAULT','Das digitale Materiallager','Materialarchiv','vault'],
['20-afterimage','THE SILENCE MUSEUM','Der digitale Nachhall','Im Steinbruch der Zeit','afterimage'],
['21-gameworld','ICARE','Eine spielbare FORMIKAT-Welt','Ich.Fahr.Rad','platformer'],
['22-levels','JAY RANSIJN','Projekte werden Levels','FORMIKAT Projekte','levels'],
['23-robot','MEET MY ROBOT','Die Projektmaschine','Werkstatt Halle','robot'],
['24-exhibit','NOOMO SHOWCASE','Die Website ist das erste Exponat','Deltaslide','exhibit'],
['25-sequence','NK STUDIO','Portfolio als Choreografie','Nach den Maschinen','sequence'],
['26-multiworld','RICARDO CHANCE','Jedes Projekt darf anders sein','FORMIKAT Multiversum','multiworld'],
['27-image-physics','FRAMEMODE','Das Bildarchiv bekommt Physik','Projektarchiv','physics'],
['28-editorial','STUDIODIALECT','Redaktion trifft Raum','Total Real','editorial'],
['29-material-interface','RESN','Ein Material statt einer Homepage','Salz / Stahl / Textil','fluid'],
['30-render-lab','FUTAMURA.DEV','30 Arbeiten, 30 digitale Regeln','FORMIKAT Render Lab','renderlab']
];

const descriptions={
'scroll-flight':'Scrollen beschleunigt die Kamera entlang einer räumlichen Projektspur.',drive:'Mit WASD oder Pfeiltasten durch die Werkstatt fahren.',house:'Ziehen dreht das unmögliche Haus; Räume reagieren als eigene Projektkörper.',panorama:'Den rekonstruierten Ausstellungsraum durch Ziehen und Hotspots erkunden.',timeline:'Scrollen legt den Entwurfsprozess Schicht für Schicht frei.',doors:'Jede Tür ist ein echtes Projektportal – anklicken und hindurchgehen.',terrain:'Mit der Maus über eine datengetriebene Projektlandschaft fliegen.',city:'Ziehen rotiert die Projektstadt; Mausrad verändert ihre Dichte.',depth:'Mit dem Scrollrad vom sichtbaren Exponat bis in Konstruktion und Recherche tauchen.',face:'Kamera erlauben oder den Zeiger bewegen: Haltung und Blick steuern die Szene.',builder:'Module ziehen, drehen und zu einer eigenen Ausstellung koppeln.',configurator:'Material, Licht und Öffnung direkt am Objekt verändern.',floorplan:'Räume im Plan anwählen und räumlich betreten.',model:'Das Architekturmodell zerlegen, drehen und wieder zusammensetzen.',garden:'Projektobjekte wachsen, wenn man sie berührt.',facets:'Zeigerbewegung verändert Geometrie, Licht und Material wie ein digitales Versuchslabor.',orbit:'Projektkörper im Orbit anwählen und die Maßstäbe wechseln.',perspective:'Dasselbe Projekt simultan als Raum, Objekt, Grafik, Technik und Aufbau lesen.',vault:'Bild- und Materialschichten aus dem räumlichen Archiv ziehen.',afterimage:'Bewegung hinterlässt Erinnerungsspuren – ein leiser digitaler Nachhall.',platformer:'Mit Pfeiltasten durch eine spielbare Ausstellungsroute springen.',levels:'Projekte als vertikale Level; Scrollen öffnet jeweils eine neue Regel.',robot:'Eine Projektmaschine aus Aufgaben zusammenbauen und in Bewegung setzen.',exhibit:'Das digitale Exponat reagiert auf Nähe, Licht und Berührung.',sequence:'Scrollen dirigiert eine präzise typografisch-räumliche Choreografie.',multiworld:'Jeder Klick wechselt in eine eigene visuelle Welt mit eigener Regel.',physics:'Projektbilder werfen, stapeln und kollidieren lassen.',editorial:'Redaktionelle Spalten werden durch Scrollen zu einem räumlichen Essay.',fluid:'Mit dem Zeiger Salz, Stahl und Textil als fließende Oberfläche verformen.',renderlab:'30 kleine Renderregeln live kombinieren und als neue Ansicht testen.'};

const common = `*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;height:100dvh;overflow:hidden;overscroll-behavior:none;background:#0d0e0d;color:#f3efe6;font-family:Arial,Helvetica,sans-serif;-webkit-user-select:none;user-select:none}body,canvas,svg,#stage{touch-action:none}canvas,svg{position:fixed;inset:0;width:100%;height:100%}.top{position:fixed;z-index:9;left:0;top:0;width:100%;display:flex;align-items:center;gap:18px;padding:max(16px,env(safe-area-inset-top)) max(18px,env(safe-area-inset-right)) 16px max(18px,env(safe-area-inset-left));mix-blend-mode:difference}.top b{letter-spacing:.12em}.top small{font:10px monospace;opacity:.7}.top a{margin-left:auto;color:inherit;text-decoration:none;border:1px solid;padding:9px 13px;border-radius:99px;min-height:44px;display:grid;place-items:center}.copy{position:fixed;z-index:8;left:max(18px,env(safe-area-inset-left));bottom:max(18px,env(safe-area-inset-bottom));max-width:min(760px,calc(100% - 36px));pointer-events:none}.copy em{font:11px monospace;font-style:normal;letter-spacing:.12em}.copy h1{font-size:clamp(42px,8vw,116px);letter-spacing:-.07em;line-height:.82;margin:12px 0 16px;text-wrap:balance}.copy p{font-size:clamp(14px,1.5vw,20px);max-width:620px;line-height:1.3}.badge{position:fixed;z-index:8;right:24px;bottom:22px;font:10px monospace;text-transform:uppercase}.hot{cursor:pointer}.hot:hover{filter:brightness(1.35)}.touch-controls{display:none;position:fixed;z-index:20;right:max(18px,env(safe-area-inset-right));bottom:max(24px,env(safe-area-inset-bottom));grid-template-columns:52px 52px 52px;grid-template-rows:52px 52px;gap:5px}.touch-controls button{border:1px solid #fff9;background:#111b;color:#fff;border-radius:50%;font-size:22px;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px)}.touch-controls [data-key="ArrowUp"]{grid-column:2}.touch-controls [data-key="ArrowLeft"]{grid-column:1;grid-row:2}.touch-controls [data-key="ArrowDown"]{grid-column:2;grid-row:2}.touch-controls [data-key="ArrowRight"]{grid-column:3;grid-row:2}.touch-hint{display:none;position:fixed;z-index:10;right:18px;top:74px;font:10px monospace;background:#111b;border:1px solid #fff5;border-radius:99px;padding:8px 12px;pointer-events:none}@media(pointer:coarse){.touch-hint{display:block}.touch-controls{display:grid}.copy{bottom:max(20px,env(safe-area-inset-bottom));max-width:calc(100% - 36px)}.copy h1{font-size:clamp(38px,11vw,58px)}.copy p{font-size:14px;max-width:72%;margin-bottom:0}.badge{display:none}}`;

const wheelModes=new Set(['scroll-flight','timeline','city','depth','orbit','levels','sequence','editorial']);
function touchUI(mode){const pad=['drive','platformer'].includes(mode)?`<div class="touch-controls" aria-label="Touch-Steuerung"><button data-key="ArrowUp">↑</button><button data-key="ArrowLeft">←</button><button data-key="ArrowDown">↓</button><button data-key="ArrowRight">→</button></div>`:'';const hint=wheelModes.has(mode)?'↕ WISCHEN':['drive','platformer'].includes(mode)?'TOUCH-STEUERUNG':'ZIEHEN · TIPPEN';return `${pad}<div class="touch-hint">${hint}</div>`}
function touchJS(mode){let js=`let __ty=null;addEventListener('pointerdown',e=>{if(e.pointerType==='touch')__ty=e.clientY},{passive:true});addEventListener('pointerup',()=>__ty=null,{passive:true});addEventListener('pointercancel',()=>__ty=null,{passive:true});`;
if(wheelModes.has(mode))js+=`addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&__ty!==null){let dy=__ty-e.clientY;dispatchEvent(new WheelEvent('wheel',{deltaY:dy*5}));__ty=e.clientY}},{passive:true});`;
if(mode==='drive')js+=`document.querySelectorAll('.touch-controls button').forEach(b=>{const off=()=>keys[b.dataset.key]=0;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=1};b.onpointerup=off;b.onpointercancel=off})`;
if(mode==='platformer')js+=`document.querySelectorAll('.touch-controls button').forEach(b=>{const off=()=>k[b.dataset.key]=0;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);k[b.dataset.key]=1};b.onpointerup=off;b.onpointercancel=off})`;
return js}
function base(p,body,script,extra='') { const [slug,ref,title,project,mode]=p; return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>FORMIKAT — ${title}</title><style>${common}${extra}</style></head><body><div class="top"><b>FORMIKAT</b><small>${slug.slice(0,2)} / 30 · ${ref}</small><a href="index.html">ALLE 30</a></div>${body}${touchUI(mode)}<div class="copy"><em>${project} · EXPERIMENT</em><h1>${title}</h1><p>${descriptions[mode]}</p></div><div class="badge">${mode.replaceAll('-',' ')} · interaktiv</div><script>${script};${touchJS(mode)}</script></body></html>` }

const canvasPrelude=`const c=document.querySelector('canvas'),x=c.getContext('2d');let W,H,d=Math.min(devicePixelRatio,2),mx=.5,my=.5,t=0;function size(){W=c.width=innerWidth*d;H=c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(d,0,0,d,0,0)}size();addEventListener('resize',size);addEventListener('pointermove',e=>{mx=e.clientX/innerWidth;my=e.clientY/innerHeight});`;

function canvasScene(mode,i){
 const seed=i+1;
 const draw={
 'scroll-flight':`let z=0;addEventListener('wheel',e=>z+=e.deltaY*.01);function a(){requestAnimationFrame(a);t+=.01;z*=.94;x.fillStyle='#101614';x.fillRect(0,0,innerWidth,innerHeight);for(let j=0;j<34;j++){let q=((j*5-t*8-z)%90+90)%90,s=900/(q+5),px=innerWidth/2+Math.sin(j*2.7)*s*2,py=innerHeight/2+Math.cos(j*1.3)*s;x.strokeStyle=j%3?'#d9ff42':'#ff4b2b';x.strokeRect(px-s,py-s*.6,s*2,s*1.2)} }a()`,
 drive:`let car={x:innerWidth/2,y:innerHeight/2,a:0,v:0},keys={};onkeydown=e=>keys[e.key]=1;onkeyup=e=>keys[e.key]=0;function a(){requestAnimationFrame(a);t+=.016;car.v+=(keys.ArrowUp||keys.w?.02:0)-(keys.ArrowDown||keys.s?.015:0);car.v*=.96;car.a+=(keys.ArrowRight||keys.d?.04:0)-(keys.ArrowLeft||keys.a?.04:0);car.x+=Math.sin(car.a)*car.v*18;car.y-=Math.cos(car.a)*car.v*18;x.fillStyle='#d9d2c5';x.fillRect(0,0,innerWidth,innerHeight);x.strokeStyle='#111';for(let j=-20;j<30;j++){x.beginPath();x.moveTo(0,j*90+(car.y%90));x.lineTo(innerWidth,j*90+(car.y%90));x.stroke()}x.save();x.translate(car.x,car.y);x.rotate(car.a);x.fillStyle='#ff4b23';x.fillRect(-15,-28,30,56);x.restore()}a()`,
 terrain:`let q=0;addEventListener('wheel',e=>q+=e.deltaY*.002);function a(){requestAnimationFrame(a);t+=.015;x.fillStyle='#07171b';x.fillRect(0,0,innerWidth,innerHeight);for(let r=0;r<28;r++){x.beginPath();for(let j=0;j<80;j++){let px=j/79*innerWidth,py=innerHeight*.28+r*17+Math.sin(j*.22+t+r*.25)*25+(my-.5)*r*5;x[j?'lineTo':'moveTo'](px,py)}x.strokeStyle=r%5?'#6ce4d1':'#ff5b35';x.globalAlpha=.8-r*.02;x.stroke()}x.globalAlpha=1}a()`,
 depth:`let dep=0;addEventListener('wheel',e=>dep=Math.max(0,Math.min(4,dep+Math.sign(e.deltaY))));function a(){requestAnimationFrame(a);x.fillStyle=['#d8f6ff','#1c7690','#06394c','#06161e','#02080b'][dep];x.fillRect(0,0,innerWidth,innerHeight);for(let j=0;j<70;j++){let px=(j*97+t*20)%innerWidth,py=(j*53)%innerHeight,r=(j%5+1)*(dep+1);x.fillStyle=j%4?'#fff8':'#ff6b44';x.beginPath();x.arc(px,py,r,0,7);x.fill()}t+=.01}a()`,
 afterimage:`x.globalCompositeOperation='source-over';function a(){requestAnimationFrame(a);x.fillStyle='#090b10';x.globalAlpha=.08;x.fillRect(0,0,innerWidth,innerHeight);x.globalAlpha=.8;for(let j=0;j<9;j++){x.strokeStyle=['#efede3','#ff623c','#7d72ff'][j%3];x.strokeRect(mx*innerWidth+Math.sin(t+j)*90-j*18,my*innerHeight+Math.cos(t*.8+j)*70-j*12,100+j*9,60+j*4)}t+=.02}a()`,
 fluid:`function a(){requestAnimationFrame(a);t+=.012;let g=x.createLinearGradient(0,0,innerWidth,innerHeight);g.addColorStop(0,'#d9d2be');g.addColorStop(.5,'#505c62');g.addColorStop(1,'#efe9dc');x.fillStyle=g;x.fillRect(0,0,innerWidth,innerHeight);for(let r=0;r<45;r++){x.beginPath();for(let j=0;j<60;j++){let px=j/59*innerWidth,dist=Math.abs(px-mx*innerWidth),py=r*18+Math.sin(j*.3+t+r*.1)*8+Math.exp(-dist/180)*(my-.5)*150;x[j?'lineTo':'moveTo'](px,py)}x.strokeStyle=r%6?'#ffffff28':'#ff5a35aa';x.stroke()} }a()`,
 renderlab:`let rule=0;addEventListener('click',()=>rule=(rule+1)%30);function a(){requestAnimationFrame(a);t+=.015;x.fillStyle='#101010';x.fillRect(0,0,innerWidth,innerHeight);for(let j=0;j<80;j++){let px=(j*83)%innerWidth,py=(j*47)%innerHeight,s=10+20*Math.sin(t+j+rule);x.save();x.translate(px,py);x.rotate(t*(rule%5-2)*.1);x.strokeStyle=['#ff512f','#e8ff42','#746cff','#f3efe6'][(j+rule)%4];x.strokeRect(-s,-s,s*2,s*2);x.restore()}x.font='120px monospace';x.fillStyle='#fff1';x.fillText(String(rule+1).padStart(2,'0'),innerWidth*.55,innerHeight*.45)}a()`
 }[mode]; return canvasPrelude+draw;
}

function domScene(mode,i){
 let body='<div id="stage"></div>', extra='#stage{position:fixed;inset:0;perspective:900px;transform-style:preserve-3d}#stage>*{position:absolute;transition:.7s cubic-bezier(.2,.8,.2,1)}';
 let js=`const s=document.querySelector('#stage');`;
 const cards=()=>`const names=['Nach den Maschinen','Zukunftswerkstatt','Total Real','MOVE!','Streit.','Im Steinbruch der Zeit','Willhelmgrill','Deltaslide'];`;
 if(mode==='house'){js+=cards()+`names.forEach((n,j)=>{let e=document.createElement('div');e.className='hot';e.textContent=n;e.style.cssText='left:50%;top:45%;width:210px;height:130px;padding:18px;background:'+['#ff4b23','#e8ff42','#746cff','#eee'][j%4]+';color:#111;transform:rotateY('+(j*45)+'deg) translateZ(280px)';s.append(e)});addEventListener('pointermove',e=>s.style.transform='rotateX('+((e.clientY/innerHeight-.5)*-25)+'deg) rotateY('+((e.clientX/innerWidth-.5)*45)+'deg)')`}
 else if(mode==='doors'){js+=cards()+`names.forEach((n,j)=>{let e=document.createElement('button');e.innerHTML='<b>'+n+'</b>';e.style.cssText='left:'+((j%4)*24+3)+'%;top:'+(Math.floor(j/4)*28+18)+'%;width:18%;height:36%;background:#111;border:8px solid '+['#ff5b38','#dfff42','#776cff','#eee'][j%4]+';color:white';e.onclick=()=>{e.style.transform='perspective(600px) rotateY(-105deg)';document.body.style.background=e.style.borderColor};s.append(e)})`}
 else if(mode==='timeline'){js+=`let steps=['IMPULS','RECHERCHE','SKIZZE','PROTOTYP','PLANUNG','BAU'];steps.forEach((n,j)=>{let e=document.createElement('section');e.innerHTML='<small>0'+(j+1)+'</small><h2>'+n+'</h2>';e.style.cssText='left:'+(j*100)+'vw;top:15vh;width:78vw;height:55vh;padding:5vw;background:'+['#ece6d8','#ff5a35','#171717','#dfff3f','#786eff','#ece6d8'][j]+';color:'+(j%3?'#111':'#111')+';font-size:6vw';s.append(e)});addEventListener('wheel',e=>{window.q=Math.max(0,Math.min(5,(window.q||0)+Math.sign(e.deltaY)));s.style.transform='translateX(-'+(window.q*100)+'vw)'})`}
 else if(mode==='builder'){js+=`let selected='STAB',parts=['STAB','KNOTEN','TEXTIL','SOCKEL','MONITOR','SOUND'];function place(z,n,x,y){let p=document.createElement('b');p.textContent=n;p.style.cssText='position:absolute;left:'+(x-30)+'px;top:'+(y-20)+'px;padding:20px;background:#eee;color:#111;transform:rotate('+(Math.random()*.3-.15)+'rad)';z.append(p)}parts.forEach((n,j)=>{let e=document.createElement('div');e.textContent=n;e.draggable=true;e.dataset.part=n;e.style.cssText='left:'+(5+j*14)+'%;top:14%;padding:18px;background:'+['#ff5b38','#dfff42','#746cff'][j%3]+';color:#111';e.ondragstart=v=>v.dataTransfer.setData('text',n);e.onpointerdown=()=>selected=n;s.append(e)});let z=document.createElement('div');z.style.cssText='left:15%;top:35%;width:70%;height:42%;border:2px dashed #fff6';z.ondragover=e=>e.preventDefault();z.ondrop=e=>{e.preventDefault();place(z,e.dataTransfer.getData('text'),e.offsetX,e.offsetY)};z.onpointerdown=e=>{if(e.pointerType==='touch')place(z,selected,e.offsetX,e.offsetY)};s.append(z)`}
 else if(mode==='floorplan'){js+=`let rooms=[['SINNE',8,12,28,28],['KLIMA',37,12,22,28],['WEIDEROUTE',62,12,30,28],['GER',8,44,24,38],['KASCHMIR',35,44,28,38],['DIALOG',66,44,26,38]];rooms.forEach((r,j)=>{let e=document.createElement('button');e.textContent=r[0];e.style.cssText='left:'+r[1]+'%;top:'+r[2]+'%;width:'+r[3]+'%;height:'+r[4]+'%;border:2px solid #eee;background:#111;color:#eee';e.onclick=()=>{s.style.transform='scale(2.5) translate('+(35-r[1])+'%,'+(35-r[2])+'%)';e.style.background='#ff5b38'};s.append(e)})`}
 else if(mode==='perspective'){js+=`let labels=['RAUM','OBJEKT','GRAFIK','TECHNIK','AUFBAU'];labels.forEach((n,j)=>{let e=document.createElement('div');e.innerHTML='<b>'+n+'</b><br>MOVE! Verkehr macht Stadt';e.style.cssText='left:'+(8+j*17)+'%;top:'+(16+j%2*18)+'%;width:22%;height:45%;padding:24px;background:'+['#ff5b38','#e4ff43','#756dff','#eee','#222'][j]+';color:'+(j===4?'#fff':'#111')+';transform:rotate('+(j-2)*3+'deg)';const open=()=>e.style.transform='scale(1.18) translateY(-30px)';e.onpointerenter=open;e.onpointerdown=open;e.onpointerleave=()=>e.style.transform='rotate('+(j-2)*3+'deg)';s.append(e)})`}
 else if(mode==='vault'){js+=cards()+`names.concat(names).forEach((n,j)=>{let e=document.createElement('div');e.textContent=n;e.style.cssText='left:'+(5+(j%8)*12)+'%;top:'+(12+Math.floor(j/8)*26)+'%;width:10%;height:20%;padding:10px;background:'+['#ddd','#b7a88e','#5f645e','#ff5a35'][j%4]+';color:#111;box-shadow:0 20px 30px #0008';e.onpointerdown=v=>{e.setPointerCapture(v.pointerId);e.onpointermove=q=>{e.style.left=q.clientX-40+'px';e.style.top=q.clientY-40+'px'}};s.append(e)})`}
 else if(mode==='sequence'||mode==='editorial'||mode==='levels'){js+=cards()+`names.forEach((n,j)=>{let e=document.createElement('article');e.innerHTML='<small>0'+(j+1)+'</small><h2>'+n+'</h2><p>Idee · Raum · Objekt · Umsetzung</p>';e.style.cssText='left:8%;top:'+(j*100+12)+'vh;width:84%;height:70vh;border-top:1px solid;padding:3vw;font-size:3vw;background:'+(j%2?'#eee;color:#111':'#111;color:#eee');s.append(e)});addEventListener('wheel',e=>{window.q=Math.max(0,Math.min(7,(window.q||0)+Math.sign(e.deltaY)));s.style.transform='translateY(-'+(window.q*100)+'vh) rotate('+(('${mode}'==='sequence')?window.q*.4:0)+'deg)'})`}
 else if(mode==='multiworld'){js+=`let worlds=[['SALZ','#eee','#111'],['STAHL','#60666b','#fff'],['TEXTIL','#e65b3b','#111'],['LICHT','#dfff40','#111'],['RAUM','#756cff','#fff']];let q=0;function show(){let w=worlds[q];s.innerHTML='<div style="inset:0;background:'+w[1]+';color:'+w[2]+';display:grid;place-items:center;font:14vw Arial;letter-spacing:-.08em">'+w[0]+'</div>';document.body.style.background=w[1]}show();addEventListener('click',()=>{q=(q+1)%worlds.length;show()})`}
 else if(mode==='robot'){js+=`let bot=document.createElement('div');bot.style.cssText='left:40%;top:25%;width:20%;height:44%;background:#dfff42;border-radius:45% 45% 20% 20%;color:#111;display:grid;place-items:center;font:18px monospace';bot.textContent='PROJEKT\\nMASCHINE';s.append(bot);['IDEEN','PLANEN','BAUEN','TESTEN'].forEach((n,j)=>{let b=document.createElement('button');b.textContent=n;b.style.cssText='left:'+(8+j*23)+'%;top:80%;padding:16px';b.onclick=()=>{bot.style.transform='rotate('+(j%2?12:-12)+'deg) scale('+(1+j*.08)+')';bot.style.background=['#ff5b38','#dfff42','#746cff','#eee'][j]};s.append(b)})`}
 return {body,extra,js};
}

function svgScene(mode){let body='<svg id="v" viewBox="0 0 1200 800"></svg>';let js=`const v=document.querySelector('#v'),N='http://www.w3.org/2000/svg';`;
 if(mode==='panorama')js+=`for(let j=0;j<16;j++){let p=document.createElementNS(N,'polygon');let a=j/16*Math.PI*2;p.setAttribute('points','600,390 '+(600+Math.cos(a)*700)+','+(390+Math.sin(a)*420)+' '+(600+Math.cos(a+.4)*700)+','+(390+Math.sin(a+.4)*420));p.setAttribute('fill',['#eee','#c9b99d','#ff623d','#1b1b1b'][j%4]);p.style.opacity=.75;v.append(p)}let q=0;addEventListener('pointermove',e=>{q=(e.clientX/innerWidth-.5)*300;v.style.transform='translateX('+q+'px) scale(1.12)'})`;
 else if(mode==='model')js+=`for(let j=0;j<24;j++){let r=document.createElementNS(N,'rect');r.setAttribute('x',300+(j%6)*90);r.setAttribute('y',180+Math.floor(j/6)*80);r.setAttribute('width',75);r.setAttribute('height',55);r.setAttribute('fill',['#eee','#ff5a38','#dfff42','#766cff'][j%4]);r.style.transformOrigin='600px 400px';v.append(r)}addEventListener('pointermove',e=>[...v.children].forEach((r,j)=>r.style.transform='translate('+(e.clientX/innerWidth-.5)*(j%6-2)*35+'px,'+(e.clientY/innerHeight-.5)*(Math.floor(j/6)-2)*35+'px) rotate('+(j%4*3)+'deg)'))`;
 else if(mode==='garden')js+=`for(let j=0;j<36;j++){let g=document.createElementNS(N,'circle');g.setAttribute('cx',50+(j*83)%1100);g.setAttribute('cy',90+(j*137)%560);g.setAttribute('r',12+j%6*5);g.setAttribute('fill',['#ff5a38','#dfff42','#766cff','#eee'][j%4]);const grow=()=>{g.setAttribute('r',80);g.style.filter='blur(2px)'};g.onpointerenter=grow;g.onpointerdown=grow;g.onpointerleave=()=>g.setAttribute('r',12+j%6*5);v.append(g)}`;
 else if(mode==='facets')js+=`for(let j=0;j<70;j++){let p=document.createElementNS(N,'polygon'),cx=(j*89)%1200,cy=(j*151)%800;p.setAttribute('points',cx+','+cy+' '+(cx+80)+','+(cy-30)+' '+(cx+45)+','+(cy+70));p.setAttribute('fill',['#ff5a38','#dfff42','#756cff','#eee'][j%4]);p.style.transition='.2s';v.append(p)}addEventListener('pointermove',e=>[...v.children].forEach((p,j)=>p.style.transform='rotate('+((e.clientX/innerWidth-.5)*(j%9)*8)+'deg) translateY('+((e.clientY/innerHeight-.5)*(j%7)*12)+'px)'))`;
 return {body,js,extra:'#v{background:#111;transition:.3s}'}
}

function special(mode){
 if(['scroll-flight','drive','terrain','depth','afterimage','fluid','renderlab'].includes(mode))return {body:'<canvas></canvas>',js:canvasScene(mode,pitches.findIndex(p=>p[4]===mode)),extra:''};
 if(['panorama','model','garden','facets'].includes(mode))return svgScene(mode);
 if(['house','doors','timeline','builder','floorplan','perspective','vault','sequence','editorial','levels','multiworld','robot'].includes(mode))return domScene(mode);
 if(mode==='face')return {body:'<canvas></canvas><video id="cam" autoplay playsinline muted></video>',extra:'#cam{position:fixed;right:20px;top:70px;width:140px;opacity:.22;transform:scaleX(-1)}',js:canvasPrelude+`navigator.mediaDevices?.getUserMedia({video:true}).then(s=>cam.srcObject=s).catch(()=>{});function a(){requestAnimationFrame(a);t+=.01;x.fillStyle='#150f18';x.fillRect(0,0,innerWidth,innerHeight);let cx=mx*innerWidth,cy=my*innerHeight;for(let j=0;j<25;j++){x.strokeStyle=['#ff5a38','#dfff42','#756cff'][j%3];x.beginPath();x.arc(cx+(j%5-2)*55,cy+(Math.floor(j/5)-2)*55,18+10*Math.sin(t+j),0,7);x.stroke()} }a()`};
 if(mode==='configurator'||mode==='exhibit')return {body:'<div id="obj"><i></i></div><div id="tools"></div>',extra:'#obj{position:fixed;left:35%;top:22%;width:30%;height:45%;background:#eee;border-radius:8px;box-shadow:0 30px 80px #000;transition:.5s;transform:perspective(700px) rotateX(55deg) rotateZ(-12deg)}#obj i{position:absolute;inset:15%;border:18px solid #ff5a38;border-radius:50%}#tools{position:fixed;right:24px;top:25%;display:grid;gap:8px}',js:`const o=document.querySelector('#obj'),t=document.querySelector('#tools');['SALZ','STAHL','LICHT','OFFEN'].forEach((n,j)=>{let b=document.createElement('button');b.textContent=n;b.onclick=()=>{o.style.background=['#e8e2d3','#656b70','#dfff42','#ff5a38'][j];o.style.transform='perspective(700px) rotateX('+(15+j*18)+'deg) rotateZ('+(-15+j*8)+'deg) scale('+(1+j*.08)+')'};t.append(b)});addEventListener('pointermove',e=>o.style.filter='brightness('+(0.6+e.clientX/innerWidth)+')')`};
 if(mode==='city'||mode==='orbit')return {body:'<canvas></canvas>',extra:'',js:canvasPrelude+`let zoom=1;addEventListener('wheel',e=>zoom=Math.max(.4,Math.min(2,zoom-e.deltaY*.001)));function a(){requestAnimationFrame(a);t+=.008;x.fillStyle='#0b1112';x.fillRect(0,0,innerWidth,innerHeight);for(let j=0;j<42;j++){let A=j/42*Math.PI*2+t,R=(90+j*8)*zoom,px=innerWidth/2+Math.cos(A+mx)*R,py=innerHeight/2+Math.sin(A)*R*.35,sz=${mode==='city'?'18+(j%8)*9':'8+(j%5)*5'};x.fillStyle=['#ff5b38','#dfff42','#756cff','#eee'][j%4];${mode==='city'?`x.fillRect(px,py-sz,sz,sz*2)`:`x.beginPath();x.arc(px,py,sz,0,7);x.fill()`}}}a()`};
 if(mode==='platformer')return {body:'<canvas></canvas>',extra:'',js:canvasPrelude+`let p={x:100,y:300,vy:0},k={};onkeydown=e=>k[e.key]=1;onkeyup=e=>k[e.key]=0;function a(){requestAnimationFrame(a);p.x+=(k.ArrowRight?5:0)-(k.ArrowLeft?5:0);if(k.ArrowUp&&p.y>innerHeight-130)p.vy=-12;p.vy+=.6;p.y+=p.vy;if(p.y>innerHeight-100){p.y=innerHeight-100;p.vy=0}x.fillStyle='#91dceb';x.fillRect(0,0,innerWidth,innerHeight);x.fillStyle='#232323';for(let j=0;j<12;j++)x.fillRect(j*170-(p.x*.25%170),innerHeight-70-(j%3)*70,130,18);x.fillStyle='#ff5b38';x.fillRect(p.x,p.y,34,50)}a()`};
 if(mode==='physics')return {body:'<canvas></canvas>',extra:'',js:canvasPrelude+`let a=Array.from({length:18},(_,j)=>({x:40+(j%6)*150,y:40+Math.floor(j/6)*100,vx:0,vy:0,w:120,h:75,c:['#eee','#ff5a38','#dfff42','#756cff'][j%4]})),drag;addEventListener('pointerdown',e=>drag=a.find(o=>e.clientX>o.x&&e.clientX<o.x+o.w&&e.clientY>o.y&&e.clientY<o.y+o.h));addEventListener('pointerup',()=>drag=null);addEventListener('pointermove',e=>{if(drag){drag.x=e.clientX-drag.w/2;drag.y=e.clientY-drag.h/2;drag.vx=(mx-.5)*10}});function f(){requestAnimationFrame(f);x.fillStyle='#111';x.fillRect(0,0,innerWidth,innerHeight);a.forEach(o=>{if(o!==drag){o.vy+=.25;o.x+=o.vx;o.y+=o.vy;if(o.y+o.h>innerHeight){o.y=innerHeight-o.h;o.vy*=-.55}if(o.x<0||o.x+o.w>innerWidth)o.vx*=-1}x.fillStyle=o.c;x.fillRect(o.x,o.y,o.w,o.h)})}f()`};
 return {body:'<canvas></canvas>',extra:'',js:canvasPrelude+`function a(){requestAnimationFrame(a);x.fillStyle='#111';x.fillRect(0,0,innerWidth,innerHeight);t+=.01}a()`};
}

for(const p of pitches){const v=special(p[4]);fs.writeFileSync(new URL(`./${p[0]}.html`,import.meta.url),base(p,v.body,v.js,v.extra));}

const links=pitches.map((p,i)=>`<a href="${p[0]}.html"><small>${String(i+1).padStart(2,'0')} · ${p[1]}</small><b>${p[2]}</b><span>${descriptions[p[4]]}</span></a>`).join('');
fs.writeFileSync(new URL('./index.html',import.meta.url),`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FORMIKAT — 30 digitale Regeln</title><style>*{box-sizing:border-box}body{margin:0;background:#ece7dc;color:#111;font-family:Arial;padding:24px}header{display:flex;justify-content:space-between;border-bottom:1px solid}h1{font-size:clamp(60px,12vw,170px);line-height:.78;letter-spacing:-.08em;margin:12vh 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));border:1px solid}.grid a{color:inherit;text-decoration:none;padding:18px;min-height:230px;border:1px solid;margin:-1px 0 0 -1px;display:flex;flex-direction:column;gap:16px;transition:.2s}.grid a:hover{background:#111;color:#eee;transform:translateY(-6px)}small{font:10px monospace}.grid b{font-size:28px;letter-spacing:-.04em}.grid span{margin-top:auto;line-height:1.35}</style></head><body><header><b>FORMIKAT</b><span>30 REFERENZEN · 30 EIGENE SYSTEME</span></header><h1>Jede Idee<br>hat ihre<br>eigene Physik.</h1><main class="grid">${links}</main></body></html>`);
